<a href="https://colab.research.google.com/github/themehmi/Colab-Files/blob/main/Narinder_Singh_(AIML).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print ("hello world")

hello world


Python

In [ ]:
num1=15
num2=12
divresult=num1/num2
print(divresult)

1.25


In [ ]:
sum=num1+num2
print(sum)

27


In [ ]:
name='Narinder'
age=18
print('My name is',name,'and my age is',age)

My name is Narinder and my age is 18


In [ ]:
square_num1=num1*num1
print(square_num1)

225


**Simple** **Interest**

In [ ]:
p=float(input("Enter value of p :"))
r=float(input('Enter value of r:'))
t=float(input('Enter value of t in year:'))
SI=p*r*t/100
print("Simple Interest is:",SI)
print(type(SI))

Enter value of p :300
Enter value of r:65
Enter value of t in year:2
Simple Interest is: 390.0
<class 'float'>


**Find area of circle ( take value of pie=3.14)**

In [ ]:
#area of circle = pie(r^2) r in cm
r=3
pie=3.14
area=pie*r*r
print(area)

28.259999999999998


In [ ]:
#find remainder of a number when divided by 6
num1=int(input("enter a number:"))
Remainder=num1%6
print(Remainder)

enter a number:6
0


In [ ]:
#cube of a number
num1=3
cube=num1*num1*num1
print(cube)

27


In [ ]:
#Compound Interest (CI=A-P) where A = P(1+R/100)^T"
P=400
T=3
R=600
A=P*(1+(R/100))**T
CI=A-P
print("Compound Interest =",CI)



Compound Interest = 136800.0


In [ ]:
#area of triangle"1/2xbxh" b and h in cm
b=12
h=11
areaTri=1/2*b*h
print(areaTri)

66.0


In [ ]:
#area of rectangle(l x b)
l=20
b=45
areaRect=l*b
print(areaRect)


900


In [ ]:
'''Distance Conversion

Convert speed and time to distance:

Distance(km)=Speed(km/h)×Time(h)'''

speed=120
time=1.5
Distance=speed*time
print(Distance)

180.0


In [ ]:
#calculate speed "distance/time"
distance=80
time=4
speed=distance/time
print(speed)

20.0


In [ ]:
'''Body Mass Index (BMI)

Take weight (kg) and height (m):

BMI=Weight/Height^2'''

weight=75
height=1.8
BMI=weight/(height**2)
print(BMI)




23.148148148148145


In [ ]:
# Write a program to convert temperature from Celsius to Fahrenheit using:
# fahr = (C * 9/5) + 32

C = int(input("Enter temp in Celsius value: "))

fahr = (C * 9/5)+32
print(fahr, "F")

Enter temp in Celsius value: 98
208.4 F


In [ ]:
#parameter of rectangle = 2(l+b) , l and b in cm
l=20
b=30
parameterRect=2*(l+b)
print(parameterRect)

100


Comparison Operator

In [ ]:
# ==,!=, <, >, <=, >=
# above are the operators
#examples
#1. "==" Equals to operator
x=10
b=20
print(x==b)

False


In [ ]:
#2."!=" Not equal Operator
x=10
b=20
print(x!=b)

True


In [ ]:
#3. Greater than ">"
x=10
b=20
print(x>b)

False


In [ ]:
#4. Smaller than "<"
x=10
b=20
print(x<b)

True


In [ ]:
#5. Smaller than equals to"<="
x=10
b=20
print(x<=b)

True


In [ ]:
#6. Greater than equals to">="
x=10
b=20
print(x>=b)

False


Logical Operators:

Logical and (A.B)

Logical or (A+B)

Logical not (!A)

In [ ]:
A=True
B=False
#and
print(A and B)
#or
print(A or B)
#not
print(not A)

False
True
False


Assignment Operators

=

+=

-=

*=

/=

**=

%=

In [ ]:

a=12
b=2
#"+="
b+=a
print(b)

14


In [ ]:
a=12
b=2
#"-="
b-=a
print(b)

-10


In [ ]:
a=12
b=2
#"*="
b*=a
print(b)

24


In [ ]:
a=2
b=12
#"/="
b/=a
print(b)

6.0


In [ ]:
a=12
b=2
#"**="
b**=a
print(b)

4096


In [ ]:
a=12
b=2
#"="
b=a
print(b)

12


In [ ]:
a=12
b=2
#"%="
b%=a
print(b)

2


Identity Operator

-is

-is not

In [ ]:
a=12
b=18
c=12
print(id(a))
print(id(b))
print(id(c))
#is
print(a is c)
#is not
print(a is not b)
print(a is b)

11654728
11654920
11654728
True
True
False


Membership Operators

In

Not In

In [ ]:

#in
a=10
b=12
list={10,16,17,18}
print(a in list)
print(b in list)
#not in
print(a not in list)
print(b not in list)

True
False
False
True


In [ ]:
text="hello python"
#in
print("h" in text)
#not in
print("h" not in text)
#in
print("h" in text[9])
#not in
print("h" not in text[9])

True
False
True
False


If-else Statements

..If

..else

..elif

In [ ]:
#program to check the number is even or odd using if else statements
num=int(input("Enter a number:"))
if num1<=0:
   print("cannot check that the number is even or odd as the number is probably a zero or a negative number")
elif num%2==0:
   print("The number is even")
else:
   print("The number is odd")

Enter a number:9
The number is odd


In [ ]:
 num=123
 print(str(num)[1])

2


In [ ]:
num=123
print(123//10%10)

2


* Loops

In [ ]:
#for loop
N=int(input("Number:"))
for i in range(2,N,5):
   print(i)

Number:50
2
7
12
17
22
27
32
37
42
47


In [ ]:
#for loop for string
word=str("Neym")
for str in word:
  print(word)
#new thing learned by mistake

Neym
Neym
Neym
Neym


In [ ]:
#for loop for string
word=("Neym")
for char in word:
  print(char)

N
e
y
m


In [ ]:
#factorial using for loop
num=int(input("Enter a Number:"))
factorial=1
for i in range (1,num+1):
   factorial*=i
   print(factorial)

Enter a Number:8
1
2
6
24
120
720
5040
40320


In [ ]:
#print numbers in reverse from 10 to 1
for i in range(-9,1):
  print(-i-(-1))

10
9
8
7
6
5
4
3
2
1


In [ ]:
for i in range(10,0,-1):
  print (i)

10
9
8
7
6
5
4
3
2
1


In [ ]:


#reverse of a number using for loop
num=int(input("Enter a number:"))
reverse=0
while num>0:
 digit=num%10
 reverse=(reverse*10)+digit
 num//=10
print(reverse)

In [ ]:
#print sum of numbers from 1 to 100
sum=0
for i in range (1,101):
 sum=sum+i
print(sum)

5050


In [ ]:
#return chosen characters
text=input("Enter a text:")
sp_char="!","?",","
for char in text:
  if char in sp_char:
   print("text contains special characters like :",sp_char)

Enter a text:hello!
text contains special characters like : ('!', '?', ',')


In [ ]:
#Find the average
sum=0
for i in range(1,51):
 sum=sum+i
 average=sum/50
print(average)

25.5


While Loop

In [ ]:
#sum of digits
num=int(input("Enter a number:"))
total=0
while num>0:
 digit=num%10
 total+=digit
 num//=10
print(total)

Enter a number:87
15


In [ ]:
#check palindrome
text=(input("Enter a text:"))
if text==text[::-1]:
   print("palindrome")
else:
   print("not palindrome")

Enter a text:lol
palindrome


In [ ]:
#count vowels
text="Narinder"
vowels="aeiouAEIOU"
count=0
for ch in text:
 if ch in vowels:
  count=count+1
print(count)

3


In [ ]:
#palindrome using loop
num=int(input("Enter a number:"))
temp=num
reverse=0
while temp>0:
 digit=temp%10
 reverse=(reverse*10)+digit
 temp//=10
if(num==reverse):
  print("Palindrome")
else:
  print("non-palindrome")

Enter a number:99
Palindrome


In [ ]:
#split a string and make it uppercase
Str_1="What's up roddy"
print(Str_1.upper().split())

["WHAT'S", 'UP', 'RODDY']


In [ ]:
#Reverse string using negative indexing
text="Neym"
print(text[::-1])

myeN


In [ ]:
#use multi line string
Name="""Neym
The
Reaper"""
print(Name)

Neym
The
Reaper


In [ ]:
#count the number of adults in a group of 6 people
adults=0
minors=0
for i in range (1,7):
 age=int(input("Enter age:"))
 if(age>=18):
     adults+=1
 else:
     minors+=1
print("Total adults:",adults)
print("Total minors:",minors)

Enter age:8
Enter age:90
Enter age:45
Enter age:16
Enter age:12
Enter age:37
Total adults: 3
Total minors: 3


In [ ]:
#age and Name verification
Birth_date=int(input("Enter Date:"))
Name=(input("Enter Name:"))
if(Birth_date==8) and (Name=="Narinder"):
 print("Verfied")
else:
 print("Verification Failed")

Enter Date:8
Enter Name:Narinder
Verfied


**Practice Questions Loops and String**

In [ ]:
#list prime numbers between 1 to N
def print_primes_in_range(start, end):
  N=10
  for num in range(start, end + 1):
        if num > 1:
            is_prime = True
            for i in range(2, int(num**0.5) + 1):
                if (num % i) == 0:
                    is_prime = False
                    break
            if is_prime:
                print(num)
start_range = 1
end_range = N
print_primes_in_range(start_range, end_range)

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47


In [ ]:
#print sum of all prime numbers between A to B
A = int(input("Enter A: "))
B = int(input("Enter B: "))

total = 0

for num in range(A, B+1):
    if num > 1:
        count = 0
        for i in range(1, num+1):
            if num % i == 0:
                count += 1
        if count == 2:
            total += num

print("Sum of primes =", total)

Enter A: 2
Enter B: 12
Sum of primes = 28


In [ ]:
#Count how many numbers between 1 to N are divisible by 3 or 5.
N=30
count=0
for i in range (1, N+1):
  if i%3==0 or i%5==0:
    count+=1
print(count)

14


In [ ]:
#Generate a multiplication table from 1 to 10 (nested loops).
for i in range(1,11):
  for j in range(1,11):
    print(i,"x",j,"=",i*j)

1 x 1 = 1
1 x 2 = 2
1 x 3 = 3
1 x 4 = 4
1 x 5 = 5
1 x 6 = 6
1 x 7 = 7
1 x 8 = 8
1 x 9 = 9
1 x 10 = 10
2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20
3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
3 x 10 = 30
4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
4 x 10 = 40
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50
6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
6 x 10 = 60
7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
7 x 10 = 70
8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72
8 x 10 = 80
9 x 1 = 9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81
9 x 10 = 90
10 x 1 = 10
10 x 2 = 20


In [ ]:
#Check if a string is a palindrome using loop.
text=(input("Enter a text:"))
rev=""
for ch in text:
 rev+=ch
print(rev)
if text==rev:
  print("Palindrome")
else:
  print("Not Palindrome")




Enter a text:lol
lol
Palindrome


In [ ]:
#Find sum of digits until the result becomes a single digit
n=95
while n>=10:
  sum=0
  while n>0:
    digit=n%10
    sum+=digit
    n//=10
  n=sum
print(sum)


5


In [ ]:
#Check if a number is an Armstrong number.
num=153
temp=num
power=len(__builtins__.str(temp))
total=0
while temp>0:
  digit=temp%10
  total+=digit**power
  temp//=10
if total==num:
  print("number is armstrong number")
else:
  print("number is not armstrong number")


number is armstrong number


In [ ]:
#Generate the first N prime numbers.

In [ ]:
#Generate the first N Fibonacci numbers using loop.

In [ ]:
#Count how many even numbers are between 1 and N.
N=int(input("Enter a number:"))
count=0
for i in range(1, N):
 if i%2==0:
  count+=1
print(count)

Enter a number:9
4


In [ ]:
#Reverse a number (e.g., 123 → 321).
N=123
reverse=0
while N>0:
  digit=N%10
  reverse=(reverse*10)+digit
  N//=10
print(reverse)

321


In [ ]:
"""For numbers 1 to N:
 If divisible by 3 print "Fizz"
 If divisible by 5 print "Buzz"
 If divisible by both 3 and 5 print "FizzBuzz"
 Else print number"""
N=int(input("Enter a number:"))
for i in range(1,N):
  if i%3==0:
    print("Fizz")
  elif i%5==0:
    print("Buzz")
  elif i%3==0 and i%5==0:
    print("FizzBuzz")
  else:
    print(i)

Enter a number:10
1
2
Fizz
4
Buzz
Fizz
7
8
Fizz


In [ ]:
#Count how many odd numbers are between 1 and N.
N=int(input("Enter a number:"))
count=0
for i in range(1, N):
 if i%2!=0:
  count+=1
print(count)

Enter a number:9
4


**Strings – Practice Questions:**

In [ ]:
#Reverse a string without using slicing.
text= "Neym"
rev=""
for ch in text:
 rev+=ch
print("Reversed Str:", rev)

Reversed Str: Neym


In [ ]:
#Check if a string is palindrome.
text=(input("Enter a text:"))
if text==text[::-1]:
   print("palindrome")
else:
   print("not palindrome")

Enter a text:lko
not palindrome


In [ ]:
#Count vowels and consonants in a string.
text="yo im narinder"
vowels="aeiouAEIOU"
vowels_c=cons_c=0
for ch in text:
 if ch in vowels:
  vowels_c+=1
 else:
  cons_c+=1
print("Vowels:",vowels_c)
print("Consonants:",cons_c)

Vowels: 5
Consonants: 9


In [ ]:
#Count number of words in a sentence.
text="im death itself"
text.split()
print(text.split())
print("total words in this sentence is:",len(text.split()))

['im', 'death', 'itself']
total words in this sentence is: 3


In [ ]:
#Convert string to uppercase without using built-in upper().
text="neym"
text.swapcase()
print(text.swapcase())

NEYM


In [ ]:
Str="the chaos"
count = 0
for char in Str:
  count += 1
print("Length of the string is:", count)

Length of the string is: 9


In [ ]:
#Check if two strings are anagrams.
text1="narinder"
text2="neaderin"
for ch in text1:
  if ch in text2:
    print("anagrams")
  else:
    print("not anagrams")

anagrams
anagrams
anagrams
anagrams
anagrams
anagrams
anagrams
anagrams


In [ ]:
#Remove spaces from a string.
String="N A R I N D E R"
print(String.replace(" ",""))

NARINDER


In [ ]:
#Count occurrences of a character in a string.
text="balpreet"
print(text.count("e"))

2


In [ ]:
#Remove digits from a string.
text="Narinder123"
new_text = ""
for ch in text:
  if not ch.isdigit():
    new_text += ch
print(new_text)

Narinder


In [ ]:
#Remove alphabets from a string.
text="Narinder123"
new_text = ""
for ch in text:
  if not ch.isalpha():
    new_text += ch
print(new_text)

123


In [ ]:
#Check if a string contains only digits.
text="123456"
print(text.isdigit())

True


In [ ]:
text="1neym6"
print(text.isdigit())

False


In [ ]:
#Replace all spaces with underscores _.
text="im death itself"
print(text.replace(" ","_"))

im_death_itself


In [ ]:
#Find first non-repeating character in a string


In [ ]:
#Check if a string is a pangram (contains all alphabets).

In [ ]:
#Sum of all even numbers in a given range
N=10
total=0
for i in range(1,N+1):
 if i%2==0:
   total+=i
print(total)

30


In [ ]:
#pascal triangle
N=4
for lineno in range(1,N+1):
  for s in range(N-lineno):
    print(" ",end=" ")
  for i in range(1,lineno+1):
    print(i, end=" ")
  for i in range(i-1, 0, -1):
    print(i , end=" ")
  print(" ")
for lineno in range(N-1 , 0 , -1) :
  for s in range(N-lineno):
    print(" " , end=" ")
  for i in range(1, lineno+1):
    print(i , end=" ")
  for i in range(i-1, 0, -1):
    print(i , end=" ")
  print(" ")

      1  
    1 2 1  
  1 2 3 2 1  
1 2 3 4 3 2 1  
  1 2 3 2 1  
    1 2 1  
      1  


In [ ]:
def add( a, *var1) :
  sum=0
  # check each parameter if int add to sum variable
  print (a)
  sum = sum  + float(a)
  for m in var1:
    #check m if int add in sum
    # if m.is
      sum = sum + float(m)
    sum=sum + m
    print(m)

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 10)

In [ ]:
add(20,m=20)

NameError: name 'add' is not defined

In [ ]:
my_list = [1, 2]

for v in range(2):
    my_list.insert(-1, my_list[v])

print(my_list)



[1, 1, 1, 2]


###Functions

In Python, a function is a reusable block of code that performs a specific task, defined using the def keyword and executed only when called.

In [ ]:
#print prime numbers using user defined function
def is_prime(start_range, end_range):
  for num in range(start_range,end_range+1):
    if num > 1:
      is_prime = True
      for i in range(2, int(num**0.5) + 1):
        if (num % i) == 0:
          is_prime = False
          break
      if is_prime:
        print(num)
        is_prime = True
start_range = 1
end_range = 10
is_prime(start_range, end_range)


2
3
5
7


In [ ]:
#check if a number is an armstrong by defining user defined function
def is_armstrong(num):
  power=len(__builtins__.str(num))
  total=0
  while num>0:
    digit=num%10
    total=total**power
    num//=10
  if total==num:
   is_armstrong=True
  else:
   is_armstrong=False
  return is_armstrong
print(is_armstrong(153))


True


In [ ]:
#check if a str is a palindrome
def is_palindrome(str):
  if str==str[::-1]:
    is_palindrome=True
  else:
    is_palindrome=False
  return is_palindrome
print(is_palindrome("dead"))

False


**Recursion**

function calling itself

code becomes concise/short

no for loop for iteration / iterates automatically

return statement

can lead to infinite loop, if the return statement is not properly placed.

In [ ]:
#sum of a digits in a number
def sum_of_digits(num):
  if num==0:
    return 0
  else:
    return num%10+ sum_of_digits(num//10)
sum_of_digits(34)

7

In [ ]:
#check palindrome
def is_palindrome(str):
  if len(str)<=1:
    return False
  else :
   str==str[::-1]
  return True
  is_palindrome("ded")

**Call by value/ reference**

**Lambda Function**

In [ ]:
#Example:
square_root= lambda x : x**2
print(square_root(10))

100


**NumPy**

In [ ]:
#Create a NumPy array with values from 1 to 10.
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#Create a NumPy array of five zeros.
import numpy as np
ar=np.zeros(5)
print(ar)


[0. 0. 0. 0. 0.]


In [ ]:
#Create a NumPy array of five ones.
import numpy as np
ar=np.ones(5)
print(ar)


[1. 1. 1. 1. 1.]


In [ ]:
#Create a NumPy array using arange() from 5 to 50 with a step of 5.
import numpy as np
ar = np.arange(5, 51, 5)
print(ar)



[ 5 10 15 20 25 30 35 40 45 50]


In [ ]:
#Create a 2D NumPy array of shape (3, 3).
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
#Find the dimension of a given NumPy array.
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.shape)
print(arr.ndim)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2


In [ ]:
#Find the shape of a NumPy array.
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
#Access the first and last element of a NumPy array.
import numpy as np
arr=np.array([1,2,3,4])
print("first element:",arr[0])
print("last element:",arr[3])

first element: 1
last element: 4


In [ ]:
#Extract the second row from a 2D NumPy array.
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print("second row:",arr[1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
second row: [4 5 6]


In [ ]:
#Extract the third column from a 2D NumPy array.
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print("third column:",arr[:,2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
third column: [3 6 9]


In [ ]:
#Add 10 to every element of a NumPy array.
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr+10)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [ ]:
#Multiply all elements of an array by 5.
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr*5)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [ ]:
#Find the sum of all elements in a NumPy array.
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(arr))

45


In [ ]:
#Find the maximum and minimum value of an array.
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.max(arr))
print(np.min(arr))

9
1


In [ ]:
#Count the total number of elements in an array.
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.size)

9


In [ ]:
#Reshape a 1D array of 12 elements into a 3×4 array.
import numpy as np
arr=np.array([6,4,3,9,5,1,9,5,3,4,2,0])
r_arr=arr.reshape(3,4)
print(r_arr)

[[6 4 3 9]
 [5 1 9 5]
 [3 4 2 0]]


In [ ]:
#sort axis
import numpy as np
arr=np.array([[1,3,6],[1,4,2]])
print(np.sort(arr))
print(np.sort(arr,axis=0))



[[1 3 6]
 [1 2 4]]
[[1 3 2]
 [1 4 6]]


In [ ]:
#Convert an integer array into a float array.
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
re_type=arr.astype(float)
print(re_type)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
#create method to populate array of n elements and return array of
import numpy as np
def populate_array(n):
  arr=np.arange(1,n+1)
  reciprocal_arr=np.reciprocal(arr)
  return arr,reciprocal_arr
print(populate_array(10))

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0]))


In [ ]:
#for float value
import numpy as np
def populate_array(n):
  arr=np.arange(1,n+1,dtype=float)
  reciprocal_arr=np.reciprocal(arr)
  return reciprocal_arr
print(populate_array(10))

[1.         0.5        0.33333333 0.25       0.2        0.16666667
 0.14285714 0.125      0.11111111 0.1       ]


In [ ]:
#angles trignometry
angles = np.array([0, np.pi/4, np.pi/2, np.pi])  # 0°, 45°, 90°, 180°
sin_values = np.sin(angles)
cos_values = np.cos(angles)

print("Angles (radians):", angles)
print("Sine values:", sin_values)
print("Cosine values:", cos_values)



Angles (radians): [0.         0.78539816 1.57079633 3.14159265]
Sine values: [0.00000000e+00 7.07106781e-01 1.00000000e+00 1.22464680e-16]
Cosine values: [ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -1.00000000e+00]


In [ ]:
import numpy as np
nn5=np.arange(1,25).reshape(6,4,order='F')
nn5

array([[ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23],
       [ 6, 12, 18, 24]])

**Assignment**

In [ ]:
# 1.Write a python program to type Hello World
print("Hello World")

Hello World


In [ ]:
# 2.Write a python program to do a arithmetical operations addition and division.
num1=int(input("Enter a number 1:"))
num2=int(input("Enter a number 2:"))
print("Addition:",num1+num2)
print("Division:",num1/num2)

Enter a number 1:6
Enter a number 2:8
Addition: 14
Division: 0.75


In [ ]:
# 3.Write a python program to find the area of a triangle
Base=int(input("Enter Base of a Triangle:"))
Height=int(input("Enter Height of a Triangle:"))
Area=1/2*Base*Height
print("Area of Triangle:",Area)

Enter Base of a Triangle:6
Enter Height of a Triangle:9
Area of Triangle: 27.0


In [ ]:
# 4.Write a python program to swap two variables
a=10
b=5
temp=a
a=b
b=temp
print(a,b)

5 10


In [ ]:
# 5.Write a python program to generate a random number
import random
a=random.randint(1,100)
print(a)

92


In [ ]:
# 6.Write a program to convert kilometres into miles
kilometres=30
print("in miles:",kilometres*0.621371)

in miles: 18.64113


In [ ]:
# 7.Write a python program to convert Celsius to Fahrenheit
C = int(input("Enter temp in Celsius value: "))

fahr = (C * 9/5)+32
print(fahr,"°F")

Enter temp in Celsius value: 98
208.4 °F


In [ ]:
# 8.Write a python program to display calendar
import calendar
year=int(input ("Enter Year:"))
month=int(input("Enter Month:"))
print(calendar.month(year,month))

Enter Year:20266
Enter Month:7
     July 20266
Mo Tu We Th Fr Sa Su
                   1
 2  3  4  5  6  7  8
 9 10 11 12 13 14 15
16 17 18 19 20 21 22
23 24 25 26 27 28 29
30 31



In [ ]:
# 9.Write a Python Program to swap variables without using temp variable
a=21
b=12
#using xor operator
a=a^b
b=b^a
a=a^b
print(a,b)

12 21


In [ ]:
# 10.Write a Python Program to check whether the number is +ve,-ve or zero
num=int(input("Enter Number:"))
if(num==0): print("number is zero")
elif(num<0): print("number is -ve")
else: print("number is +ve")

Enter Number:7
number is +ve


In [ ]:
# 11.rite a Python Program to Check if a Number is Odd or Even.
num=int(input("Enter Number:"))
if(num%2==0):
  print("number is even")
else:
  print("number is odd")

Enter Number:9
number is odd


In [ ]:
# 12.Write a Python Program to Check Leap Year
year=int(input("Enter Year:"))
if(year%4==0):
  print("leap year")
else:
  print("not a leap year")

Enter Year:2026
not a leap year


In [ ]:
# 13.Write a Python Program to Check Prime Number
def is_prime(num):
  for i in range(2,int(num**(0.5)+1)):
    if num%i==0:
      return False
  return True
num = int(input("Enter a number: "))
if is_prime(num):
    print("prime")
else:
    print("not prime")

Enter a number: 7
prime


In [ ]:
# 14.Write a Python Program to Print all Prime Numbers in an Interval of 1-10.
def print_primes_in_range(start_range, end_range):
  for num in range(start_range,end_range+1):
    if num > 1:
      is_prime = True
      for i in range(2, int(num**0.5) + 1):
        if (num % i) == 0:
          is_prime = False
          break
      if is_prime:
        print(num)
        is_prime = True
start_range = 1
end_range = 10
print_primes_in_range(start_range, end_range)


2
3
5
7


In [ ]:
# 15.Write a Python Program to Find the Factorial of a Number.
num=int(input("Enter Number:"))
factorial=1
for i in range(1,num+1):
  factorial=factorial*i
print(factorial)


Enter Number:7
5040


In [ ]:
# 16.Write a Python Program to Display the multiplication Table.
num=int(input("Enter Number:"))
for i in range(1,11):
  print(num,"x",i,"=",num*i)

Enter Number:9
9 x 1 = 9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81
9 x 10 = 90


In [ ]:
# 17.Write a Python Program to Find Armstrong Number in an Interval.
for i in range(1,200):
  digits=(__builtins__.str(i))
  power=len(__builtins__.str(i))
  total=0
  for d in digits:
    total=total+int(d)**power
  if total==i:
   print(i)


1
2
3
4
5
6
7
8
9
153


In [ ]:
# 18.Write a Python Program to Find the Sum of Natural Numbers.
num=int(input("Enter Number:"))
sum=0
if num<1:
  print("invalid input")
for i in range(1,num+1):
  sum=sum+i
print("Sum of natural numbers in an interval:",sum)

Enter Number:12
Sum of natural numbers in an interval: 78


In [ ]:
# 19.Write a Python Program to Convert Decimal to Binary, Octal and Hexadecimal.
#using builtin fucntions
decimal=int(input("Enter decimal Number:"))
print("Binary:",bin(decimal).replace("0b",""))
print("Octal:",oct(decimal).replace("0o",""))
print("Hexadecimal:",hex(decimal).replace("0x",""))

Enter decimal Number:12
Binary: 1100
Octal: 14
Hexadecimal: c


In [ ]:
# 20.How can we manually convert a decimal number to binary, octal and hexadecimal?
#manually binary
decimal = int(input("Enter a decimal number: "))
num = decimal
binary = ""
if num == 0:
    binary = "0"
else:
    while num > 0:
        binary = __builtins__.str(num % 2) + binary
        num //= 2
print(binary)

Enter a decimal number: 9
1001


In [ ]:
#manually octal
decimal = int(input("Enter a decimal number: "))
num = decimal
octal = ""
if num == 0:
    octal = "0"
else:
    while num > 0:
        octal = __builtins__.str(num % 8) + octal
        num //= 8
print(octal)

Enter a decimal number: 32
40


In [ ]:
#manually hexadecimal
decimal = int(input("Enter a decimal number: "))
num = decimal
hex_digits = "0123456789ABCDEF"
hexadecimal = ""
if num == 0:
    hexadecimal = "0"
else:
    while num > 0:
        remainder = num % 16
        hexadecimal = hex_digits[remainder] + hexadecimal
        num //= 16
        print(hexadecimal)

Enter a decimal number: 14
E


In [ ]:
# 21. a. Divide 27 by 2. Quotient is 13, remainder is 1. Note the remainder.
num=27
steps=[]
while num>0:
  quotient=num//2
  remainder=num%2
  steps.append((remainder))
  print(num,"/",2,"=",quotient,"remainder=",remainder)
  num=quotient
  binary="".join(__builtins__.str(bit) for bit in reversed(steps))
print(binary)




27 / 2 = 13 remainder= 1
13 / 2 = 6 remainder= 1
6 / 2 = 3 remainder= 0
3 / 2 = 1 remainder= 1
1 / 2 = 0 remainder= 1
11011


In [ ]:
# 22. b.Divide 13 by 2. Quotient is 6, remainder is 1. Note the remainder.
num=13
steps=[]
while num>0:
  quotient=num//2
  remainder=num%2
  steps.append((remainder))
  print(num,"/",2,"=",quotient,"remainder=",remainder)
  num=quotient
  binary="".join(__builtins__.str(bit) for bit in reversed(steps))
print(binary)

13 / 2 = 6 remainder= 1
6 / 2 = 3 remainder= 0
3 / 2 = 1 remainder= 1
1 / 2 = 0 remainder= 1
1101


In [ ]:
# c.Divide 6 by 2. Quotient is 3, remainder is 0. Note the remainder.
num=6
steps=[]
while num>0:
  quotient=num//2
  remainder=num%2
  steps.append((remainder))
  print(num,"/",2,"=",quotient,"remainder=",remainder)
  num=quotient
  binary="".join(__builtins__.str(bit) for bit in reversed(steps))
print(binary)

6 / 2 = 3 remainder= 0
3 / 2 = 1 remainder= 1
1 / 2 = 0 remainder= 1
110


In [ ]:
# d.Divide 3 by 2. Quotient is 1, remainder is 1. Note the remainder
num=3
steps=[]
while num>0:
  quotient=num//2
  remainder=num%2
  steps.append((remainder))
  print(num,"/",2,"=",quotient,"remainder=",remainder)
  num=quotient
  binary="".join(__builtins__.str(bit) for bit in reversed(steps))
print(binary)

3 / 2 = 1 remainder= 1
1 / 2 = 0 remainder= 1
11


In [ ]:
# e.Divide 1 by 2. Quotient is 0, remainder is 1. Note the remainder.
num=1
steps=[]
while num>0:
  quotient=num//2
  remainder=num%2
  steps.append((remainder))
  print(num,"/",2,"=",quotient,"remainder=",remainder)
  num=quotient
  binary="".join(__builtins__.str(bit) for bit in reversed(steps))
print(binary)

1 / 2 = 0 remainder= 1
1


In [ ]:
#octal
# f. Divide 27 by 8. Quotient is 3, remainder is 3. Note the remainder.
num=27
steps=[]
while num>0:
  quotient=num//8
  remainder=num%8
  steps.append((remainder))
  print(num,"/",8,"=",quotient,"remainder=",remainder)
  num=quotient
  octal="".join(__builtins__.str(bit) for bit in reversed(steps))
print(octal)

27 / 8 = 3 remainder= 3
3 / 8 = 0 remainder= 3
33


In [ ]:
# g. Divide 3 by 8. Quotient is 0, remainder is 3. Note the remainder.
num=3
steps=[]
while num>0:
  quotient=num//8
  remainder=num%8
  steps.append((remainder))
  print(num,"/",8,"=",quotient,"remainder=",remainder)
  num=quotient
  octal="".join(__builtins__.str(bit) for bit in reversed(steps))
print(octal)

3 / 8 = 0 remainder= 3
3


In [ ]:
# hexaoctal
# h. Divide 27 by 16. Quotient is 1, remainder is 11 (B in hexadecimal). Note the remainder.
digits = "0123456789ABCDEF"
num=27
steps=[]
while num>0:
  quotient=num//16
  remainder=num%16
  steps.append((digits[remainder]))
  print(num,"/",8,"=",quotient,"remainder=",digits[remainder])
  num=quotient
  hexaoctal="".join(__builtins__.str(bit) for bit in reversed(steps))
print(hexaoctal)


27 / 8 = 1 remainder= B
1 / 8 = 0 remainder= 1
1B


In [ ]:
# 23.Write a Python Program to Make a Simple Calculator with 4 basic mathematical operations.
print("Operations:")
print("1. add")
print("2. subtract")
print("3. multiply")
print("4. divide")
choice=int(input("Enter choice:"))
num1=int(input("Enter first number:"))
num2=int(input("Enter second number:"))
if choice==1:
  print("sum:",num1+num2)
elif choice==2:
  print("difference:",num1-num2)
elif choice==3:
  print("product:",num1*num)
elif choice==4:
    print("quotient:",num1/num2)

Operations:
1. add
2. subtract
3. multiply
4. divide
Enter choice:4
Enter first number:9
Enter second number:3
quotient: 3.0


In [ ]:
# 24.Write a Python Program to Display Fibonacci Sequence Using Recursion.
def fibonacci(n):
    if n <= 0:
        return "Invalid input! Please enter a positive integer."
    elif n == 1:
        return 0
    elif n == 2:
        return 1
    else:
        return fibonacci(n-1) + fibonacci(n-2)

terms = int(input("Enter the number of terms: "))

print("Fibonacci sequence:")
for i in range(1, terms+1):
     print(fibonacci(i), end=" ")

Enter the number of terms: 9
Fibonacci sequence:
0 1 1 2 3 5 8 13 21 

In [ ]:
# 25.Write a Python Program to find largest element in an array.
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.max(arr))


9


In [ ]:
#26.Write a Python Program for array rotation.
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.rot90(arr))

[[3 6 9]
 [2 5 8]
 [1 4 7]]


In [ ]:
# 27.Write a Python Program to Split the array and add the first part to the end?
def split(arr, pos):

 first_part=arr[:pos]
 second_part=arr[pos:]
 result=second_part+first_part
 return result
arr=([[1,2,3],[4,5,6],[7,8,9]])
pos=int(input("Enter position:"))
print(split(arr,pos))


Enter position:1
[[4, 5, 6], [7, 8, 9], [1, 2, 3]]


In [ ]:
# 28.Write a Python Program to check if given array is Monotonic.
#29.A monotonic array is one that is entirely non-increasing or non-decreasing.
def is_monotonic(arr):
  increasing=decreasing=True
  for i in range(1, len(arr)):
        if arr[i] > arr[i-1]:
            decreasing = False
        if arr[i] < arr[i-1]:
            increasing = False
            return increasing or decreasing
arr1 = [1, 2, 2, 3]
arr2 = [6, 5, 4, 4]
arr3 = [1, 3, 2]

print(arr1,":",is_monotonic(arr1))
print(arr2,":",is_monotonic(arr2))
print(arr3,":",is_monotonic(arr3))

[1, 2, 2, 3] : None
[6, 5, 4, 4] : True
[1, 3, 2] : False


In [ ]:
# 30.Write a Python Program to Add Two Matrices.
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[1,0,0],[0,1,0],[0,0,1]])
print(arr1+arr2)

[[ 2  2  3]
 [ 4  6  6]
 [ 7  8 10]]


In [ ]:
# 31.Write a Python Program to Multiply Two Matrices.
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[1,0,0],[0,1,0],[0,0,1]])
print(arr1*arr2)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [ ]:
# 32.Write a Python Program to Transpose a Matrix.
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("original:",arr1)
print("transpose:",arr1.T)

original: [[1 2 3]
 [4 5 6]
 [7 8 9]]
transpose: [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
# 33.Write a Python Program to Sort Words in Alphabetic Order.
def sort_words(sentence):
    words = sentence.split()
    words.sort()
    return words
sentence = input("Enter a sentence: ")
print("sorted words:")
for word in sort_words(sentence):
    print(word)

Enter a sentence: hello balpreet
sorted words:
balpreet
hello


In [ ]:
# 34.Write a Python Program to Remove Punctuation From a String.
def remove_punctuation(text):
    result = ""
    punctuations = '''!()-[]{},;:\''""<>./?@#$%^&*_~'''
    for char in text:
        if char not in punctuations:
            result += char
    return result
text = input("Enter a string: ")
print("string without punctuation:",remove_punctuation(text))

Enter a string: helloo!
string without punctuation: helloo


In [ ]:
# 35.Write a Python program to print all disarium numbers between 1 to 100.
for i in range(1,200):
  digits=(__builtins__.str(i))
  length=len(__builtins__.str(i))
  total=0
  for d in range(length):
        total += int(digits[d]) ** (d+1)
  if total==i:
   print(i)


1
2
3
4
5
6
7
8
9
89
135
175


In [ ]:
# 36.Write a Python program to print all happy numbers between 1 and 100.


In [ ]:
#37.Write a Python program to Multiply all numbers in the list.
lst=[1,6,6,4,8]
result=1
for num in lst:
  result=result*num
print(result)

1152


In [ ]:
#38.Write a Python program to find smallest number in a list.
lst=[3,2,8,6,4,0]
print(min(lst))

0


In [ ]:
#39.Write a Python program to find largest number in a list.
lst=[3,2,8,6,4,0]
print(max(lst))

8


In [ ]:
# 40.Write a Python program to find second largest number in a list.
lst=[3,2,8,6,4,0]
print(sorted(lst)[-2])

6


In [ ]:
#41.Write a Python program to find N largest elements from a list.
lst=[3,2,8,6,4,0]
n=int(input("Enter N:"))
print(sorted(lst)[-(n)])

Enter N:2
6


In [ ]:
#42.Write a Python program to print even numbers in a list.
lst=[3,2,8,6,4,0]
for num in lst:
  if num%2==0:
   print("even:",num,end= " ")

even: 2 even: 8 even: 6 even: 4 even: 0 

In [ ]:
#43.Write a Python program to print odd numbers in a List
lst=[3,2,8,6,4,0]
for num in lst:
  if num%2!=0:
   print("odd:",num,end= " ")

odd: 3 

In [ ]:
#44.Write a Python program to Remove empty List from List.
lst=[1,4,5,[],6,[]]
new_lst=[]
for num in lst:
  if num!=[]:
    new_lst=new_lst+[num]
print(new_lst)

[1, 4, 5, 6]


In [ ]:
#.45.Write a Python program to Cloning or Copying a list.
lst=[3,2,8,6,4,0]
lst2=lst.copy()
print(lst2)
print(id(lst))
print(id(lst2))

[3, 2, 8, 6, 4, 0]
133866945019648
133866945012544


In [ ]:
#46.Write a Python program to Count occurrences of an element in a list.
lst=[3,6,8,6,2,5]
print(lst.count(6))

2


In [ ]:
#47.Write a Python program to find words which are greater than given length k.
list_1=["Neym","Raven","Narinder","Balpreet"]
list_2=[]
for words in list_1:
  if len(__builtins__.str(words))>5:
    list_2=list_2+[words]
print(list_2)

['Narinder', 'Balpreet']


In [ ]:
#48.Write a Python program for removing Ith character from a string.
text="sNeym"
lth=int(input("Enter position:"))
print(text[:lth]+text[lth+1:])

Enter position:0
Neym


In [ ]:
#49.Write a Python program to split and join a string.
Str="Neym The Reaper"
Str1=Str.split()
print(Str1)
print("Join:","-".join(Str1))

['Neym', 'The', 'Reaper']
Join: Neym-The-Reaper


In [ ]:
#50.Write a Python program to check if a given string is binary string or not.
string_1="01100"
for ch in string_1:
  if ch!='0' and ch!='1':
    print("not binary")
    break
else:
  print("binary")

binary


In [ ]:
#51.Write a Python program to find uncommon words from two Strings.
string_1="Hello! Narinder"
string_2="Hello!"
words1=string_1.split()
words2=string_2.split()
uncommon=[]
for word in words1:
  if word not in words2:
    uncommon=uncommon+[word]
print(uncommon)

['Narinder']


In [ ]:
#52.Write a Python program to find all duplicate characters in string
def find_duplicates(s):
    seen = __builtins__.set()
    duplicates = __builtins__.set()
    for char in s:
        if char not in seen:
            seen.add(char)
        else:
            duplicates.add(char)
    return __builtins__.list(duplicates)
print(find_duplicates("Hello"))

['l']


In [ ]:
#53.Write a Python Program to check if a string contains any special character.
text=input("Enter a text:")
for char in text:
  if char.isalnum():
    print("text")
  else:
    print("special character")


Enter a text:hellooo
text
text
text
text
text
text
text


In [ ]:
#54.Write a Python program to Extract Unique dictionary values.
dict1 = {"a": 10, "b": 20, "c": 10, "d": 30, "e": 20}

unique_values = []
for v in dict1.values():
    if v not in unique_values:
        unique_values.append(v)

print("Unique values:", unique_values)

Unique values: [10, 20, 30]


In [ ]:
#55.Write a Python program to find the sum of all items in a dictionary.
dict1 = {"a": 10, "b": 20, "c": 10, "d": 30, "e": 20}
print(__builtins__.sum(dict1.values()))

90


In [ ]:
#56.Write a Python program to Merging two Dictionaries.
dict1={"name":"narinder"}
dict2={"class":"AIML"}
print(dict1|dict2)

{'name': 'narinder', 'class': 'AIML'}


In [ ]:
#57.Write a Python program to convert key-values list to flat dictio]nary.
key_value_list = [("name", "narinder"), ("age", 19)]
flat_dict = dict(key_value_list)
print(flat_dict)

{'name': 'narinder', 'age': 19}


In [ ]:
#58.Write a Python program to insertion at the beginning in OrderedDict
from collections import OrderedDict
dict1 = OrderedDict([("a", 10), ("b", 20), ("c", 10), ("d", 30), ("e", 20)])
dict1["f"]=4
dict1.move_to_end("f",last=False)
print(dict1)


OrderedDict({'f': 4, 'a': 10, 'b': 20, 'c': 10, 'd': 30, 'e': 20})


In [ ]:
#59.Write a Python program to check order of character in string using OrderedDict().
def check_order(string, pattern):
    pos =0
    for char in string:
        if pos < len(pattern) and char == pattern[pos]:
            pos += 1

    return pos == len(pattern)
print(check_order("Hello","el"))


True


In [ ]:
#60.Write a Python program to sort Python Dictionaries by Key or Value.
diict={"Name":"Narinder","Class":"AIML"}
print(dict(sorted(diict.items())))


{'Class': 'AIML', 'Name': 'Narinder'}


In [ ]:
#61.Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array.
import numpy as np
X=3
Y=5
array=[]
for i in range(X):
  row=[]
  for j in range(Y):
    row.append(i*j)
  array.append(row)
print("Generated 2D array:")
for row in array:
  print(row)

Generated 2D array:
[0, 0, 0, 0, 0]
[0, 1, 2, 3, 4]
[0, 2, 4, 6, 8]


In [ ]:
##62.Write a program that accepts a comma separated sequence of words asinput and prints the words in a comma-separated sequence after sorting them alphabetically.
words = input("Enter comma-separated words: ")
word_list = words.split(",")
word_list.sort()
sorted_words = ",".join(word_list)
print("Sorted words:", sorted_words)



Enter comma-separated words: hello,neym,bye
Sorted words: bye,hello,neym


In [ ]:
#63.Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically.
words = input("Enter whitespace-separated words: ")
word_list = words.split()
unique_sorted=sorted(set(word_list))
print("Result:"," ".join(unique_sorted))


Enter whitespace-separated words: hello neym dawg
Result: dawg hello neym


In [ ]:
#64.Define a class with a generator which can iterate the numbers, which are divisible by 7, between a given range 0 and n.

In [ ]:
import numpy as np
group_people=np.array(["Parkash","Narinder","Neym","Balpreet","Sapna","Gurmej"])
age=np.array([95,19,19,20,49,82])
old=[]
young_middle_age=[]
#output the name and age
for i in range(len(group_people)):
  print(group_people[i],age[i])
print("Eligibilty for pension:")
for j in range(len(group_people)):
  if age[j]>60:
    print(group_people[j],": eligible for pension")
  else:
    print(group_people[j],": requirements not meet")
#separate according to age group
for k in range(len(group_people)):
  if age[k]>60:
    old.append((group_people[k]))
  else:
    young_middle_age.append((group_people[k]))
print(young_middle_age)
print(old)

Parkash 95
Narinder 19
Neym 19
Balpreet 20
Sapna 49
Gurmej 82
Eligibilty for pension:
Parkash : eligible for pension
Narinder : requirements not meet
Neym : requirements not meet
Balpreet : requirements not meet
Sapna : requirements not meet
Gurmej : eligible for pension
[np.str_('Narinder'), np.str_('Neym'), np.str_('Balpreet'), np.str_('Sapna')]
[np.str_('Parkash'), np.str_('Gurmej')]


**Pandas**

In [ ]:
# creating a dataframe
data={
    'Name': ["Narinder","Balpreet","Navjot","Prateek","Jaspinder","Sukhraj"],
    'Class': ["AIML","MRIT","M.COM","CSE","D.CSE","BCA"],
    'Qualification': ["12th","12th","B.Com","12th","12th","12th"],
    'DOB': ["08th July,2006", "13th May,2005","Null","16th August,2007","Null","Null"]
}
import pandas as pd
df=pd.DataFrame(data)
df

Name  Class Qualification               DOB
0   Narinder   AIML          12th    08th July,2006
1   Balpreet   MRIT          12th     13th May,2005
2     Navjot  M.COM         B.Com              Null
3    Prateek    CSE          12th  16th August,2007
4  Jaspinder  D.CSE          12th              Null
5    Sukhraj    BCA          12th              Null

In [ ]:
#custom indexing
df=pd.DataFrame(data,index=['A','B','C','D','E','F'])
df


Name  Class Qualification               DOB
A   Narinder   AIML          12th    08th July,2006
B   Balpreet   MRIT          12th     13th May,2005
C     Navjot  M.COM         B.Com              Null
D    Prateek    CSE          12th  16th August,2007
E  Jaspinder  D.CSE          12th              Null
F    Sukhraj    BCA          12th              Null

In [ ]:
#head() operator
df.head(3)

Name  Class Qualification             DOB
A  Narinder   AIML          12th  08th July,2006
B  Balpreet   MRIT          12th   13th May,2005
C    Navjot  M.COM         B.Com            Null

In [ ]:
#tail()
df.tail(3)

Name  Class Qualification               DOB
D    Prateek    CSE          12th  16th August,2007
E  Jaspinder  D.CSE          12th              Null
F    Sukhraj    BCA          12th              Null

In [ ]:
#describe
df.describe()

Name Class Qualification   DOB
count          6     6             6     6
unique         6     6             2     4
top     Narinder  AIML          12th  Null
freq           1     1             5     3

In [ ]:
#info
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, A to F
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Name           6 non-null      object
 1   Class          6 non-null      object
 2   Qualification  6 non-null      object
 3   DOB            6 non-null      object
dtypes: object(4)
memory usage: 412.0+ bytes


In [ ]:
df.shape

(6, 4)

In [ ]:
#print only columns:
df.columns


Index(['Name', 'Class', 'Qualification', 'DOB'], dtype='object')

In [ ]:
#select columns
DOB=df['DOB']
DOB

A      08th July,2006
B       13th May,2005
C                Null
D    16th August,2007
E                Null
F                Null
Name: DOB, dtype: object

Loading CSV

In [ ]:
#method 1 (Colab Native File Upload)
df=pd.read_csv('panda1.csv')
df

\nName  Class Qualification               DOB
0   Narinder   AIML          12th    08th July,2006
1   Balpreet   MRIT          12th     13th May,2005
2     Navjot  M.COM         B.Com              Null
3    Prateek    CSE          12th  16th August,2007
4  Jaspinder  D.CSE          12th              Null
5    Sukhraj    BCA          12th              Null

In [ ]:
#method 2 from github
df=pd.read_csv('https://raw.githubusercontent.com/themehmi/csv-s/refs/heads/main/panda1.csv')
df

\nName  Class Qualification               DOB
0   Narinder   AIML          12th    08th July,2006
1   Balpreet   MRIT          12th     13th May,2005
2     Navjot  M.COM         B.Com              Null
3    Prateek    CSE          12th  16th August,2007
4  Jaspinder  D.CSE          12th              Null
5    Sukhraj    BCA          12th              Null

In [ ]:
#method 3 from gdrive
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/AIML/panda1.csv')

df


Mounted at /content/drive


\nName  Class Qualification               DOB
0   Narinder   AIML          12th    08th July,2006
1   Balpreet   MRIT          12th     13th May,2005
2     Navjot  M.COM         B.Com              Null
3    Prateek    CSE          12th  16th August,2007
4  Jaspinder  D.CSE          12th              Null
5    Sukhraj    BCA          12th              Null

In [ ]:
#kaggle
import kagglehub
path=kagglehub.dataset_download("themehmi/pandas")
path

100%|██████████| 321/321 [00:00<00:00, 454kB/s]

Extracting files...


'/root/.cache/kagglehub/datasets/themehmi/pandas/versions/1'

In [ ]:
df=pd.read_csv('/root/.cache/kagglehub/datasets/themehmi/pandas/versions/1/panda1.csv')
df

\nName  Class Qualification               DOB
0   Narinder   AIML          12th    08th July,2006
1   Balpreet   MRIT          12th     13th May,2005
2     Navjot  M.COM         B.Com              Null
3    Prateek    CSE          12th  16th August,2007
4  Jaspinder  D.CSE          12th              Null
5    Sukhraj    BCA          12th              Null

##Iris Project

In [ ]:
import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/themehmi/datasets/refs/heads/main/Iris.csv")
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
#count
df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [ ]:
df[['sepal_length',	'sepal_width',	'petal_length',	'petal_width']].corr()


sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.109369      0.871754     0.817954
sepal_width      -0.109369     1.000000     -0.420516    -0.356544
petal_length      0.871754    -0.420516      1.000000     0.962757
petal_width       0.817954    -0.356544      0.962757     1.000000

In [ ]:
df[['sepal_length',	'sepal_width',	'petal_length',	'petal_width']].cov()

sepal_length  sepal_width  petal_length  petal_width
sepal_length      0.685694    -0.039268      1.273682     0.516904
sepal_width      -0.039268     0.188004     -0.321713    -0.117981
petal_length      1.273682    -0.321713      3.113179     1.296387
petal_width       0.516904    -0.117981      1.296387     0.582414

In [ ]:
#feature engineering
df['petal_area']=df['petal_length']*df['petal_width']
df.head()

sepal_length  sepal_width  petal_length  petal_width species  petal_area
0           5.1          3.5           1.4          0.2  setosa        0.28
1           4.9          3.0           1.4          0.2  setosa        0.28
2           4.7          3.2           1.3          0.2  setosa        0.26
3           4.6          3.1           1.5          0.2  setosa        0.30
4           5.0          3.6           1.4          0.2  setosa        0.28

In [ ]:
#check numpy
import numpy as np
print(np.__version__)

2.0.2


**Converting Text Labels to Numbers**

Machine learning models work with numbers, not text. We convert flower names into numeric labels.



In [ ]:
url = 'https://raw.githubusercontent.com/themehmi/datasets/refs/heads/main/Iris1.csv'
# convert in numpy array
import numpy as np
raw_data = np.genfromtxt(url, delimiter=",", dtype=str)
# Remove empty rows
raw_data = raw_data[~np.any(raw_data == '', axis=1)]
X = raw_data
print(X)

[['5.1' '3.5' '1.4' '0.2' 'setosa']
 ['4.9' '3' '1.4' '0.2' 'setosa']
 ['4.7' '3.2' '1.3' '0.2' 'setosa']
 ['4.6' '3.1' '1.5' '0.2' 'setosa']
 ['5' '3.6' '1.4' '0.2' 'setosa']
 ['5.4' '3.9' '1.7' '0.4' 'setosa']
 ['4.6' '3.4' '1.4' '0.3' 'setosa']
 ['5' '3.4' '1.5' '0.2' 'setosa']
 ['4.4' '2.9' '1.4' '0.2' 'setosa']
 ['4.9' '3.1' '1.5' '0.1' 'setosa']
 ['5.4' '3.7' '1.5' '0.2' 'setosa']
 ['4.8' '3.4' '1.6' '0.2' 'setosa']
 ['4.8' '3' '1.4' '0.1' 'setosa']
 ['4.3' '3' '1.1' '0.1' 'setosa']
 ['5.8' '4' '1.2' '0.2' 'setosa']
 ['5.7' '4.4' '1.5' '0.4' 'setosa']
 ['5.4' '3.9' '1.3' '0.4' 'setosa']
 ['5.1' '3.5' '1.4' '0.3' 'setosa']
 ['5.7' '3.8' '1.7' '0.3' 'setosa']
 ['5.1' '3.8' '1.5' '0.3' 'setosa']
 ['5.4' '3.4' '1.7' '0.2' 'setosa']
 ['5.1' '3.7' '1.5' '0.4' 'setosa']
 ['4.6' '3.6' '1' '0.2' 'setosa']
 ['5.1' '3.3' '1.7' '0.5' 'setosa']
 ['4.8' '3.4' '1.9' '0.2' 'setosa']
 ['5' '3' '1.6' '0.2' 'setosa']
 ['5' '3.4' '1.6' '0.4' 'setosa']
 ['5.2' '3.5' '1.5' '0.2' 'setosa']
 ['5.2' '3.4

In [ ]:
print("Dataset shape:", X.shape)
print("First 5 rows:\n", X[:5])

Dataset shape: (150, 5)
First 5 rows:
 [['5.1' '3.5' '1.4' '0.2' 'setosa']
 ['4.9' '3' '1.4' '0.2' 'setosa']
 ['4.7' '3.2' '1.3' '0.2' 'setosa']
 ['4.6' '3.1' '1.5' '0.2' 'setosa']
 ['5' '3.6' '1.4' '0.2' 'setosa']]


Converting Text Labels to Numbers

Machine learning models work with numbers, not text. We convert flower names into numeric labels.

In [ ]:
X = raw_data[:, :4].astype(float)
y_text = raw_data[:, 4]
print(y_text)
classes, y = np.unique(y_text, return_inverse=True)
print("Classes:", classes)
print("Numeric labels (first 10):", y[:10])

['setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'v

Basic Statistics on Real Data

In [ ]:
print("Mean:", X.mean(axis=0))
print("Std:", X.std(axis=0))
print("Min:", X.min(axis=0))
print("Max:", X.max(axis=0))

Mean: [5.84333333 3.054      3.75866667 1.19866667]
Std: [0.82530129 0.43214658 1.75852918 0.76061262]
Min: [4.3 2.  1.  0.1]
Max: [7.9 4.4 6.9 2.5]


Boolean Masking (Filtering Data by Class)

In [ ]:
setosa = X[y == 0]
versicolor = X[y == 1]
virginica = X[y == 2]

print("Setosa samples:", setosa.shape)
print("Versicolor samples:", versicolor.shape)
print("Virginica samples:", virginica.shape)

Setosa samples: (50, 4)
Versicolor samples: (50, 4)
Virginica samples: (50, 4)


Feature Normalization
Normalization makes features comparable in scale.

In [ ]:
X_mean = X.mean(axis=0)
X_std = X.std(axis=0) + 1e-8

X_norm = (X - X_mean) / X_std

print("Mean after normalization:", X_norm.mean(axis=0))
print("Std after normalization:", X_norm.std(axis=0))

Mean after normalization: [-1.79088226e-15 -2.00348997e-15 -1.47067543e-15 -9.84397749e-16]
Std after normalization: [0.99999999 0.99999998 0.99999999 0.99999999]


Correlation Matrix
Correlation tells us how features are related.

In [ ]:
corr = np.corrcoef(X_norm.T)
print(corr)

[[ 1.         -0.10936925  0.87175416  0.81795363]
 [-0.10936925  1.         -0.4205161  -0.35654409]
 [ 0.87175416 -0.4205161   1.          0.9627571 ]
 [ 0.81795363 -0.35654409  0.9627571   1.        ]]
